### ISSUE TITLE
v0.6.3 broken (libyaml-cpp.so.* files not included)

### ISSUE THREAD

**Issue by fkloosterman** [conda-forge/yaml-cpp-feedstock#3]
The yaml-cpp 0.6.3 package for linux appears to be broken because the libyaml-cpp.so.* files are not included (unlike in the 0.6.2 version, which does work for me).

**Comment by allanleal** [comment]
@seanyen Did you experience this as well? I cannot work on this this week; are you able to sort this out?

**Comment by seanyen** [comment]
@allanleal It seems there is a new `CMake` flag `YAML_BUILD_SHARED_LIBS` added in `0.6.3` which is required for correctly making the shared libraries builds.
